Squashed commit of the following:
commit 9532d3c5385f04b5a3a37ad251481ff814065b47
Merge: 8f572871b 91bc6bfd3
Author: Husky <1556047610@qq.com>
Date:   Mon Feb 6 09:25:43 2023 +0800

    Merge remote-tracking branch 'upstream/master'

commit 91bc6bfd328b8135ec579cf372f735a49b6680a0
Author: fishg <1423545+fishg@users.noreply.github.com>
Date:   Sun Feb 5 13:05:48 2023 +0800

    mt76x2: fix for 6.1 (#10863)

commit 60178fd03d9714fa98c87035efe5283c4de0cbc0
Author: Tsenghan <zhenghand@qq.com>
Date:   Sat Feb 4 21:54:27 2023 +0800

    Define domain request parameter "Line" as default (#10862)

    In Action "DescribeSubDomainRecords", define argument “Line” to the specific "defalut". This is for someone who have two or more same domain names but in different dns request source(ISP), but return more than 1 record will goto print "地址需要修改".  For document of  aliyun API, set a Line parament can solve this issue because most of users just have one ISP for each domain and its value was set as "default".

commit b597493248d56be6b25d46a4c03108f084ff014b
Author: Beginner <70857188+Beginner-Go@users.noreply.github.com>
Date:   Sat Feb 4 21:45:21 2023 +0800

    wwan/app: code alignment (#10850)

    Signed-off-by: Beginner-Go <70857188+Beginner-Go@users.noreply.github.com>

commit 1daa71c00586ce156ac420b8d06a3d9081f51b7c
Author: coolsnowwolf <coolsnowwolf@gmail.com>
Date:   Thu Feb 2 23:55:49 2023 +0800

    quectel_QMI_WWAN: port to linux 6.1 support

commit de25320d7a99ca1e0cb87ca67cb30d63f0fdc3c2
Author: coolsnowwolf <coolsnowwolf@gmail.com>
Date:   Thu Feb 2 19:50:19 2023 +0800

    Version update to R23.2.14

commit a8b2e68da8664be451d8617e06b127cb378996e3
Author: coolsnowwolf <coolsnowwolf@gmail.com>
Date:   Thu Feb 2 19:43:57 2023 +0800

    package: add wwan Quectel modem packages and luci

commit f143a1598544ee93830cab248fded4e5ad5f1eb3
Author: 1054009064 <44148148+1054009064@users.noreply.github.com>
Date:   Thu Feb 2 16:39:58 2023 +0800

    ipq807x: add tl-er2260t dts for other device builds in 5.15 (#10846)

    Only solves other device builds, doesn't support tl-er2260t running.

commit 27a331a57b43bbe2f694eb38755e5404da25f1d4
Author: coolsnowwolf <coolsnowwolf@gmail.com>
Date:   Thu Feb 2 12:46:12 2023 +0800

    autocore: fix sfp unplugged speed display

commit f6d0acb91ba3377579b6604b7d65368c1a34e204
Author: 1054009064 <44148148+1054009064@users.noreply.github.com>
Date:   Thu Feb 2 12:42:41 2023 +0800

    qca-ssdk: refresh patches (#10845)

    Fixed patch application failure.

    Fixes: 89200af ("bump qca-ssdk nss-dp and ssdk-shell, Add tplink-tl-er2260t basic support (#10777)")
    Fixes: #10844

commit 89200afb014415772555e61efcb30509eae5948b
Author: qlugcp <122597754+qlugcp@users.noreply.github.com>
Date:   Thu Feb 2 01:26:55 2023 +0800

    bump qca-ssdk nss-dp and ssdk-shell, Add tplink-tl-er2260t basic support (#10777)

    * bump qca-nss-dp and ssdk ssdk-shell to 12.1

    * [qca-ssdk] delete 0008 patch as 12.1 version do not need this

    * [ipq807x]: Add support for tplink-tl-er2260t(basic)

    * remove unused parts in 2260t.dts

    * NSS:bump nss-drv64 to 12.1r2 (may affect ipq806x)

    * fix nss-dp source_url

    * qca-ssdk: refresh ssdk patch

commit 26b859543a2bd11441ad78ac0cb21ffd98d4fde5
Author: lovehackintosh <92633080+lovehackintosh@users.noreply.github.com>
Date:   Wed Feb 1 18:21:28 2023 +0800

    kernel: bump to 5.10.166, 5.15.91, 6.1.9 (#10842)

    * kernel: bump 5.15 to 5.15.91

    * kernel: bump 6.1 to 6.1.9

    * kernel: bump 5.10 to 5.10.166

commit 7fea68185c376ba1aada64281f2b3e4701b51f7f
Author: coolsnowwolf <coolsnowwolf@gmail.com>
Date:   Wed Feb 1 17:18:22 2023 +0800

    kernel: bump 6.1 to 6.1.9

commit 912696441b49fe1da8eb9d6f21068673a5291955
Author: coolsnowwolf <coolsnowwolf@gmail.com>
Date:   Tue Jan 31 15:06:50 2023 +0800

    rtl8812au-ac: backport linux kernel 6.1 support

commit fb0c3a7fdefbbb1c517840b4b875fccd88c48563
Author: coolsnowwolf <coolsnowwolf@gmail.com>
Date:   Tue Jan 31 13:27:15 2023 +0800

    rtl8812au-ac: port RTL8812AU/21AU and RTL8814AU Wireless drivers from aircrack-ng

commit ff68c93d9b6bfdf4ed564eb1c4df6586542e303e
Author: Lollipop907 <34392880+Lollipop907@users.noreply.github.com>
Date:   Tue Jan 31 12:55:50 2023 +0800

    rockchip:fix build failure and change network for MPC1903 (#10837)

    * Update armv8.mk

    * Update 02_network

commit 0fbb5e9fd31ff2e0309da40e85f4829baeff7170
Author: zfdx <47835976+zfdx123@users.noreply.github.com>
Date:   Tue Jan 31 11:40:11 2023 +0800

    ramips: hiwifi-r33: fix partition and led (#10836)

commit 8f572871b67d86a66331592328c0c83c70ce1982
Merge: 894a10706 e20fa327e
Author: Husky <1556047610@qq.com>
Date:   Mon Jan 30 10:40:40 2023 +0800

    Merge remote-tracking branch 'upstream/master'

commit e20fa327ec50487856ca43a65a44c022266715c9
Author: 骷髅头 <74764072+DHDAXCW@users.noreply.github.com>
Date:   Sun Jan 29 19:35:47 2023 +0800

    uqmi:fix build failure (#10831)

    ERROR: package/network/utils/uqmi failed to build.

commit 7d2c1575bec86dd98248ac06229a98f79adf9f46
Author: Hugo Chen <ttcf15@163.com>
Date:   Sun Jan 29 12:20:04 2023 +0800

    ci: update upload-artifact (#10824)

commit 4a50778a190e38a00b76c770f2cad3ef8f2cc798
Author: xiaotan8 <62252056+xiaotan8@users.noreply.github.com>
Date:   Sun Jan 29 12:18:40 2023 +0800

    uqmi: bump to latest git HEAD (#10826)

commit 894a10706a3a2ae569836e08fce66b806cf87561
Merge: a35f71abe fec4f5df6
Author: Husky <1556047610@qq.com>
Date:   Fri Jan 27 22:37:44 2023 +0800

    Merge remote-tracking branch 'upstream/master'

commit fec4f5df67b2794020d5e622f02ce9186f985acf
Author: Nick Hainke <vincent@systemli.org>
Date:   Mon Oct 10 08:04:41 2022 +0200

    kernel: test for kernel version greater 5.13 to fix mmc-spi

    The of_mmc_spi.o resource is provider agnostic in kernels greater 5.13
    and does not depend anymore on CONFIG_OF.

    Fixes: #10769

    Suggested-by: John Thomson <git@johnthomson.fastmail.com.au>
    Signed-off-by: Nick Hainke <vincent@systemli.org>

commit ccc69944452c28efbffe5c847e17113e37579cba
Author: coolsnowwolf <coolsnowwolf@gmail.com>
Date:   Thu Jan 26 21:15:53 2023 +0800

    toolchain/gcc: revert to version 11 by default